@startuml deploiement
title EduSphere : diagramme de déploiement
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam ArrowColor #0B1E3D
skinparam roundcorner 8
skinparam nodeBackgroundColor #F7F9FC
skinparam nodeBorderColor #0B1E3D
skinparam databaseBackgroundColor #E3ECF6

node "Poste de l'utilisateur" {
  component "Navigateur web\n(ordinateur ou téléphone)" as NAV
}
cloud "Render (hébergement)" {
  node "edusphere-frontend\n(conteneur Docker)" {
    component "nginx 1.27" as NGINX
    artifact "Application React 18\n(Vite, fichiers statiques)" as SPA
  }
  node "edusphere-backend\n(conteneur Docker)" {
    component "API Node.js 20 / Express 4" as API
    component "Sequelize 6 (ORM)" as ORM
    component "pdfkit (documents PDF)" as PDFK
  }
  database "PostgreSQL\n(edusphere-db)" as PG
}
cloud "Services e-mail" {
  component "SendGrid / Resend\n(API HTTPS)" as MAIL
}

NAV --> NGINX : HTTPS
NGINX --> SPA
NGINX --> API : /api et /fichiers\n(proxy HTTPS)
API --> ORM
API --> PDFK
ORM --> PG : SQL (SSL)
API --> MAIL : HTTPS
@enduml
